apiVersion: v1
kind: Service
metadata:
  name: ftp-service
spec:
  selector:
    app: ftp
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
    - protocol: TCP
      port: 21000
      targetPort: 21000
    - protocol: TCP
      port: 21010
      targetPort: 21010
  type: LoadBalancer

